spring.application.name=pix

#configs mongodb
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=pix_db
spring.data.mongodb.username=admin
spring.data.mongodb.password=password
spring.data.mongodb.uuid-representation=standard

logging.level.root=INFO
logging.level.com.pix=DEBUG
logging.file.name=logs/application.log
